conversation:
  initiate:
    agent_phone_number: "+33612345678" # Phone number the bot will transfer the call to if customer asks for a human agent
    bot_company: Contoso
    bot_name: Amélie
    lang: {}

communication_services:
  phone_number: "+33612345678" # Phone number purshased from Communication Services

sms:
  mode: telnyx
  telnyx:
    api_key: your_telnyx_api_key_v2
    phone_number: "+1234567890"

prompts:
  llm: {}
  tts: {}
